packages:
  - "apps/*"
  - "integrations/*/frontend"
  - "integrations/*/backend"
  - "packages/*"
  - "packages/lib/*"
  - "packages/features/*/frontend"
  - "packages/features/*/backend"

catalog:
  typescript: 5.9.2
  vitest: ^2.1.8
  "@types/node": ^24.0.0
  next: ^16.0.0
